# Automatically generated by configure - do not modify
SRC_PATH=/home/benzene/sslab/kvm/code/qemu-guest/qemu-arm-0.15.1/roms/vgabios
CC=arm-none-linux-gnueabi-gcc
BCC=bcc
CPP=arm-none-linux-gnueabi-cpp
OBJCOPY=objcopy
IASL=iasl
LD=arm-none-linux-gnueabi-ld
